#pragma once

#include "DxLib.h"

#define GAME_WIDTH 800
#define GAME_HEIGHT 600
#define GAME_COLOR 32

#define GAME_WINDOW_NAME "GAME TITLE"
#define GAME_WINDOW_MODE TRUE

#define SET_WINDOW_ST_MODE_DEFAULT 0
#define SET_WINDOW_ST_MODE_TITLE_NONE 1
#define SET_WINDOW_ST_MODE_TITLE_FLAME_NONE 2
#define SET_WINDOW_ST_MODE_FLAME_NONE 3

#define GAME_FPS_SPEED